# Site-wide settings
# ------------------
#
title: olaf's site
url: "https://grette.org"

author:
  name: Olaf Grette
  email: olaf@grette.org
#
# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
description: >
 Personal site and blog of Olaf Grette: software engineer and life long tinkerer.
 I promise to sometimes make posts. Views and opinions expressed within are my own
 and don't reflect the views of my employer, management chain, god himself, and so on.

# Build settings
# --------------
#
# If you wish to use the gem-version of Minima with or without a Gemfile, use
#   the following setting:
# theme: minima
#
# **OR** if you wish to use the theme directly from the GitHub repository by
#   bypassing a Gemfile, use the following setting instead.
#   It is best that you lock to a particular commit and update if uptream changes
#   do not affect your site adversely.
remote_theme: jekyll/minima@d4d779a
#
# Minima requires the following plugins:
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme
#
# Uncomment the following setting if you wish to disable deprecation warnings
#   from newer versions of sass converter. Adapt as required.
# sass:
#   quiet_deps: true
#   silence_deprecations: [import]


# Minima-specific settings (applicable to Minima v3 and above only)
# -----------------------------------------------------------------
#
#  *All described config keys below should be nested under the top-level
#   `minima` key.*
#
minima:
#   Minima skin selection. Available skins are:
#     * classic            Default, light color scheme.
#     * dark               Dark variant of the classic skin.
#     * auto               Adaptive skin based on the classic and dark skins.
#     * solarized-light    Light variant of solarized color scheme.
#     * solarized-dark     Dark variant of solarized color scheme.
#     * solarized          Adaptive skin for solarized color scheme skins.
  skin: dark  
#
#   Specific pages for site navigation.
#     If you wish to link only specific pages in the site-navigation, use this
#     and list the `path` property (as represented via Liquid) of the pages in
#     the order they should be rendered.
  nav_pages:
    - about.md
#
#   Set to `true` to show excerpts on the homepage.
  show_excerpts: true
#
#   Minima date format.
#     The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
#     Refer to https://shopify.github.io/liquid/filters/date/ for valid values
  date_format: "%b-%d-%Y"
#
#   Social Media Links.
#     Renders icons via Font Awesome Free webfonts CDN, based on ordered list of
#     entries. Valid entry keys:
#       * title    Tooltip rendered on hovering over icon.
#       * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
#       * url      Full URL of social profile.
  social_links:
    - title: olaf@grette.org
      icon: envelope
      url: "mailto:olaf@grette.org"
    - title: olafgrette@github
      icon: github
      url: "https://github.com/olafgrette"
    - title: olafgrette@linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/olafgrette/"
#     - title: Jekyll at X (formerly Twitter)
#       icon: x-twitter
#       url: "https://x.com/jekyllrb"
#
#   Hide syndication feed subscription link.
#     RSS / Atom feed link is always rendered as the last item of social-links
#     list. Set below key to `true` to not have the link to feed rendered as
#     part of social-links list.
  hide_site_feed_link: false
